### ISSUE TITLE
Failing when adding/downloading some podcast

### ISSUE THREAD

**Issue by tanja84dk** [xthursdayx/docker-gpodder#2]
I tried to export the subscribed list from gpodder on a laptop to then import the list on the docker container, and tried also with my export from overcast on my mobile with same issue.

But for some reason I’m getting a lot of ansii error in the docker log and also podcasts from ancher is directly reporting 404 even that they worked on the laptop

I’m able to give you the opml file if you can’t to test your self

Here is a snippet from docker logs on the container

UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
1597242660.918769 [gpodder.extensions] ERROR: Error in /usr/share/gpodder/extensions/tagging.py in on_episode_downloaded: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/extensions.py", line 83, in handler
    cb_res = callback(*args, **kwargs)
  File "/usr/share/gpodder/extensions/tagging.py", line 185, in on_episode_downloaded
    self.write_info2file(info, episode)
  File "/usr/share/gpodder/extensions/tagging.py", line 262, in write_info2file
    audio.insert_coverart()
  File "/usr/share/gpodder/extensions/tagging.py", line 170, in insert_coverart
    data = open(self.cover).read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

**Comment by tanja84dk** [comment]
This error is also popping up in the log when ever I try to import the complete export


Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 1301, in on_treeview_query_tooltip
    if not getattr(treeview, TreeViewHelper.CAN_TOOLTIP) or x > 50 or (column is not None and column != treeview.get_columns()[0]):
AttributeError: 'TreeView' object has no attribute '_gpodder_can_tooltip'
1597262338.664160 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 1301, in on_treeview_query_tooltip
    if not getattr(treeview, TreeViewHelper.CAN_TOOLTIP) or x > 50 or (column is not None and column != treeview.get_columns()[0]):
AttributeError: 'TreeView' object has no attribute '_gpodder_can_tooltip'

**Comment by xthursdayx** [comment]
Not sure what is going on, but I assume it may be an issue with the base imagine. I'll look into it and see if I can figure out what's going on.

**Comment by tanja84dk** [comment]
I have uploaded my opml file from overcast to my old school Dropbox account if you want it to test with because didn't knew how to share it to you on github, but bear in mind some of the podcasts are +18 topics


https://www.dropbox.com/sh/25zl9ytkrw1sjzz/AAAWiiChNr4DmYR2wQBAyGAoa?dl=0

**Comment by xthursdayx** [comment]
Okay, I looked into it and was able to reproduce the same issue. I think that the problem may be an issue with gPodder itself, rather than this docker container image, so I'll check with the gPodder devs to confirm this.

**Comment by tanja84dk** [comment]
Just wanted to check up if there has been any updates on the situation?

**Comment by xthursdayx** [comment]
Hey, sorry for the delay, work is very busy right now. Unfortunately this seems to be an issue with the way that the Guacamole base image I'm using is handling some ascii characters. I've been in touch with the developers of that image but we haven't figured it out yet. I will continue to work on it though.

**Comment by xthursdayx** [comment]
@tanja84dk Turns out I was wrong and I was able to fix this issue after all!! I just pushed a new build to Docker Hub. I tried it out with your opml file and it seemed to work without any issues. If you could pull the new version and try it out when you get a chance I'd appreciate it. Cheers!

**Comment by tanja84dk** [comment]
Sure ofc and no problem at all. I'm going to test it within 30 minutes when my zoom meeting is over

**Comment by tanja84dk** [comment]
It looks like the ascii issue has cleared up in the newest release, but I do still se many errors and podcasts from anchor is still failing.

I'm going to try to see if I'm able to export the docker container log to see if I'm able to spot the issue.

But a good thing is that it looks like it's not crashing/freezing after the ascii fix.

So thanks a lot for your great work

**Comment by xthursdayx** [comment]
Great, I'm glad that the ascii issue is solved at least. I'm going to close this issue in that case. Feel free to open a new issue related to the other issue(s). Cheers!

**Comment by tanja84dk** [comment]
Sorry work got in the way
I actually thinks that the docker image also is missing some python libraries/modules from apt because this is also spammed in the log.

1600499551.203012 [gpodder.extensions] ERROR: Error in /usr/share/gpodder/extensions/tagging.py in on_episode_downloaded: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/extensions.py", line 83, in handler
    cb_res = callback(*args, **kwargs)
  File "/usr/share/gpodder/extensions/tagging.py", line 185, in on_episode_downloaded
    self.write_info2file(info, episode)
  File "/usr/share/gpodder/extensions/tagging.py", line 262, in write_info2file
    audio.insert_coverart()
  File "/usr/share/gpodder/extensions/tagging.py", line 170, in insert_coverart
    data = open(self.cover).read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

But unfortunally I don't know if that also were a issue before because because the container hang/crashed.
